services:
  api:
    container_name: backend3
    build: 
      context: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - esioverflow-network

  # frontend:

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./Nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./Nginx/nginx.crt:/etc/nginx/ssl/nginx.crt:ro  # Chemin vers le certificat SSL
  #     - ./Nginx/nginx.key:/etc/nginx/ssl/nginx.key:ro  # Chemin vers la clé SSL
  #   depends_on:
  #     - api
  #     # - frontend

  db:
    container_name: postgres-sql3
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgres/data:rw
    networks:
      - esioverflow-network
    environment:
      - POSTGRES_USER=esioverflow
      - POSTGRES_DB=esioverflow
      - POSTGRES_PASSWORD=7488
  
volumes:
  pgdata:

networks:
  esioverflow-network:
    driver: bridge  