spring:
  application:
    name: backend
    
  #profiles:
    #active: dev
  

  datasource:
    url: jdbc:postgresql://db:5432/esioverflow
    username: esioverflow
    password: 7488
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
      #ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect